server.default_listen_address=0.0.0.0
server.bolt.listen_address=0.0.0.0:7687
dbms.routing.default_router=SERVER
server.metrics.enabled=true
server.metrics.jmx.enabled=true
server.metrics.prefix=neo4j
server.metrics.filter=*
server.metrics.csv.interval=5s
internal.dbms.cypher_ip_blocklist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.169.0/24,fc00::/7,fe80::/10,ff00::/8
dbms.security.procedures.unrestricted=gds.*,apoc.*,bloom.*
dbms.security.http_auth_allowlist=/,/browser.*,/bloom.*
dbms.security.procedures.allowlist=apoc.*,gds.*,bloom.*
