  Neo4jPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'neo4j/${AWS::StackName}/password'
      Description: !Sub 'Neo4j admin password for stack ${AWS::StackName}'
      SecretString: !Ref Password
      Tags:
        - Key: StackID
          Value: !Ref 'AWS::StackId'
        - Key: "aws-apn-id"
          Value: "pc:4t4a9h39qkq4tbo3n9zd51p25"
